/*
 * Hospital Contracts Api
 *
 * Hospital Contract Management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpikartova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package contracts

import (
	"github.com/gin-gonic/gin"
)

type HospitalContractsAPI interface {


    // CreateContract Post /api/contracts
    // Saves new contract 
     CreateContract(c *gin.Context)

    // DeleteContract Delete /api/contracts/:contractId
    // Deletes specific contract 
     DeleteContract(c *gin.Context)

    // GetContract Get /api/contracts/:contractId
    // Provides details of a single contract 
     GetContract(c *gin.Context)

    // GetContracts Get /api/contracts
    // Provides the list of hospital contracts 
     GetContracts(c *gin.Context)

    // UpdateContract Put /api/contracts/:contractId
    // Updates specific contract 
     UpdateContract(c *gin.Context)

}