/*
 * Hospital Contracts Api
 *
 * Hospital Contract Management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpikartova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package contracts

type Contract struct {

	// Unique identifier of the contract
	ContractNumber string `json:"contractNumber"`

	// Name of the contract
	Name string `json:"name"`

	// Name of the external partner
	Partner string `json:"partner"`

	// Date from which the contract is valid
	ValidFrom string `json:"validFrom"`

	// Date until which the contract is valid
	ValidUntil string `json:"validUntil"`

	// Total budget of the contract in EUR
	Budget float32 `json:"budget"`

	// Current status of the contract
	Status string `json:"status"`

	// Type of service provided under the contract
	ServiceType string `json:"serviceType,omitempty"`

	// Optional description or notes about the contract
	Description string `json:"description,omitempty"`
}
